---
- name: sftp-server role
  hosts: all
  # remote_user: root
  become: yes
  become_user: root
  vars:
    - home_partition: "{{ vpc }}"
    - sftp_users:
      - name: polar
        password: $1$polar_sa$/6pQ6vhK/Y1NbZ1vuhSmj/
        shell: False
        sftp_directories:
        - gp
        - rp
    - sftp_directories:
      - gp1
      - rp1
  roles:
    - sftp-server
