---
- name: sftp-server role
  hosts: all
  # remote_user: root
  become: yes
  become_user: root
  vars:
    - sftp_users:
      - name: polar
        password: $1$somesalt$jezmI5TSY7mVTzHLgsK5L.
        shell: False
        sftp_directories:
        - polar_data
    - sftp_directories:
      - imports
      - exports
      - { name: public, mode: 755 }
      - other
  roles:
    - sftp-server