---
- name: sftp-server role
  hosts: all
  remote_user: root
  # become: yes
  # become_user: root
  vars:
    - sftp_users:
      - name: polar
        password: "$1$salty$li5TXAa2G6oxHTDkqx3Dz/" # passpass
        shell: False
        sftp_directories:
        - polar_data
    - sftp_directories:
      - imports
      - exports
      - { name: public, mode: 755 }
      - other
  roles:
    - sftp-server