---
sftp_home_partition: "/mnt/bookingtest-validation-{{ home_partition }}-data"
sftp_group_name: sftpusers
sftp_directories: []
sftp_allow_passwords: True
sftp_enable_selinux_support: False
sftp_enable_logging: False
sftp_nologin_shell: /sbin/nologin
